services:
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql_core
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: data_infrastructure
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d:z
      - mysql_data:/var/lib/mysql:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    container_name: flask_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app:z
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: data_infrastructure
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
    command: python app.py

  tests:
    build: ./backend
    container_name: flask_tests
    profiles:
      - test_only
    environment:
      MONGO_URI: mongodb://root:root_password@mongo:27017/shopdb?authSource=admin
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: data_infrastructure
      REDIS_HOST: redis
      PYTHONPATH: .
    volumes:
      - ./backend:/app:z
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: pytest tests/ -v

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: shopdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo_init:/docker-entrypoint-initdb.d:z

volumes:
  mongo_data:
  mysql_data:
  redis_data:
