services:
  db:
    image: mysql:8.0
    container_name: mysql_core
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: data_infrastructure
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:z
      - mysql_data:/var/lib/mysql:z

volumes:
  mysql_data:

